# Generated by Django 4.1.1 on 2022-09-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('qualifications', models.CharField(max_length=200)),
                ('experience', models.CharField(max_length=200)),
                ('reporting_to', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'job',
            },
        ),
    ]
